INTRO_QUESTIONS = [
    "Tell me about your background and how it led you to pursue {career}.",
    "What drew you to {domain} work in the first place?",
    "How would you summarize your career journey around {skill}?",
    "What are your top priorities when choosing a {career} role?",
    "What is one professional strength that defines how you approach {domain} challenges?",
    "Describe your current role and what parts of it involve {skill}.",
    "How has your perspective on {career} changed over time?",
    "What personal values do you bring to {domain} teams?",
    "How do you stay motivated in the early stages of a project in {career}?",
    "What excites you most about growth opportunities in {domain}?",
    "How did your education and early experience prepare you for {skill} tasks?",
    "What is something you learned quickly when you started in {career}?",
    "Describe an achievement that best illustrates your talents in {domain}.",
    "What are your long-term goals within {career}?",
    "What is one thing you want the interviewer to know about your {skill} approach?",
    "What professional identity do you associate most with in {domain}?",
    "What is your preferred working style when contributing to a {project} in {career}?",
    "How do you define success in a role focused on {skill}?",
    "How has your transition into {domain} from your previous experience influenced your approach?",
    "How have you used {experience} to shape your career path?",
    "What is the most rewarding part of your {career} work?",
    "How do you prioritize tasks in a typical day working with {skill}?",
    "What kind of team do you perform best in for {domain} initiatives?",
    "Tell me about your origin story in {career}.",
    "How does your personal mission align with {domain} goals?",
    "What is one professional project that gave you confidence in your {skill} abilities?",
    "What do you think sets your {career} profile apart from peers?",
    "How has {experience} influenced your core working habits?",
    "What kind of leadership has supported your success in {domain}?",
    "What have you done to bridge gaps in your {skill} knowledge?",
    "How do you keep your self-development on track in {career}?",
    "What part of {experience} do you enjoy explaining most?",
    "What value do you bring to teams solving {domain} problems?",
    "How do you frame your personal strengths during introductions as a {career} candidate?",
    "What is one growth moment from a recent {project} you’d highlight?",
    "What makes you enthusiastic about this position in {domain}?",
    "How do you describe your communication style in non-technical {career} settings?",
    "What do you want your future manager to know about your {skill} mindset?",
    "What soft skill has supported your progress in {domain} most?",
    "How have you adapted to change in your {career} path?",
    "What is your approach to balancing deep work and collaboration in {domain}?",
    "How did you evaluate the cultural fit of your last {career} employer?",
    "How does your {experience} enable you to be agile as a professional?",
    "What does a strong first 90 days look like for you in a {career} role?",
    "What is your biggest career motivator when working on {project}?",
    "How have you improved your workflow around {skill} over time?",
    "How do you stay current with trends in {domain}?",
    "What do you hope to achieve in your next {career} position?",
    "How do you define your personal brand for {domain} hiring?"
]

HR_QUESTIONS = [
    "Describe a time you needed to make a tough decision at work involving {skill}.",
    "What steps do you take to ensure accountability in {project} situations?",
    "How do you handle conflict when team members disagree about {domain} priorities?",
    "Talk about a moment when you received difficult feedback and how you responded.",
    "How do you keep morale high when {experience} is slow to show progress?",
    "Tell us about a time you had to realign expectations with stakeholders on {project}.",
    "What strategies do you use when your workload in {career} is overwhelming?",
    "How do you stay organized while managing multiple {domain} commitments?",
    "Describe a time you took ownership of an error and learned from it.",
    "How do you balance attention to detail and efficiency in {skill} work?",
    "Tell me about your process for setting goals in a new {career} role.",
    "How do you adapt when plans change midstream in {project} work?",
    "Share an example of supporting someone else’s growth in your team.",
    "What have you done to promote inclusion during collaborative {domain} meetings?",
    "How do you respond to changing performance metrics in your {career} function?",
    "What is your approach to managing stress during high-pressure {project} phases?",
    "How do you decide when to escalate an issue in a {domain} environment?",
    "Describe a time you took initiative without being asked while working on {skill}.",
    "How do you maintain transparency about progress and roadblocks in {experience}?",
    "What have you learned from failure in a prior {project}?",
    "How do you keep your positive mindset through challenging {career} periods?",
    "How do you ask for help when you’re stuck on a {domain} challenge?",
    "Talk about your last performance review and what you changed afterwards.",
    "What methods do you use to support cross-functional collaboration?",
    "How do you build trust quickly with a new leader or peer?",
    "Describe a tough interpersonal situation and what you did to resolve it.",
    "What do you do when you disagree with management direction in {career}?",
    "How do you ensure your team is aligned during {project} kickoff?",
    "Talk about a time you balanced ambition with realism in {experience}.",
    "How do you manage your own development plan in {domain}?",
    "What would you do if a project’s scope shifted due to budget changes?",
    "What is your preferred way to request constructive feedback?",
    "Describe a time when you had to support someone else through a difficult period.",
    "What did you learn from your most meaningful professional mentorship experience?",
    "How do you handle a situation where expectations were undefined for {skill} tasks?",
    "How do you adjust your communication style for different audiences in {career}?",
    "Describe how you maintain a healthy work/life balance in {domain}.",
    "Tell me about a time you managed a challenging stakeholder in {experience}.",
    "How do you maintain energy when repetitive work in {project} is required?",
    "What approach do you take for fair recognition of team contributions?",
    "How do you respond when you see a teammate needing support?",
    "What do you do to maintain ethical standards in decisions about {skill}?",
    "Describe a time you had to navigate company politics to move a project forward.",
    "How would you handle being assigned a task outside your {domain} comfort zone?",
    "What is your method for clarifying ambiguous objectives in {career} work?",
    "Talk about an instance where collaboration produced a better outcome than working alone.",
    "How do you handle missed deadlines while keeping stakeholders informed?",
    "What are your strategies for encouraging a safe environment for sharing new ideas?",
    "How do you stay congruent with organizational values in your day-to-day duties?"
]

SKILL_TEMPLATES = [
    "Explain your experience with {skill}.",
    "How have you applied {skill} in a real-world context?",
    "What tools do you prefer for {skill} and why?",
    "Describe a result you achieved using {skill}.",
    "How do you keep your knowledge of {skill} up to date?",
    "When did you first start using {skill}?",
    "How do you measure success when applying {skill}?",
    "Describe an unexpected challenge you solved using {skill}.",
    "What is the most advanced {skill} work you have done?",
    "How do you teach others about {skill}?",
    "How do you prioritize {skill} tasks under pressure?",
    "What are common misconceptions about {skill}?",
    "Describe how you have combined {skill} with another competency.",
    "How would you explain {skill} to a non-expert stakeholder?",
    "What criteria do you use to choose the right {skill} approach?",
    "What is an example of {skill} driving business impact?",
    "How does your proficiency in {skill} compare to your other strengths?",
    "How much of your time is dedicated to honing {skill} in your day-to-day?",
    "Describe a time you pivoted strategy during a {skill} effort.",
    "What frameworks have supported your {skill} work?",
    "How have you documented processes involving {skill}?",
    "How have you applied {skill} in cross-domain settings?",
    "What was a key learning from an early {skill} project?",
    "How do you approach risk mitigation with {skill} implementations?",
    "What would you do differently in your most recent {skill} assignment?",
    "How do you keep quality high in {skill} deliverables?",
    "What is your favorite example of leveraging {skill} effectively?",
    "How do you assess readiness for {skill} deployment?",
    "How do you integrate {skill} into broader team objectives?",
    "How have you balanced speed vs accuracy in {skill} work?",
    "Describe a time you advocated for resources to improve {skill} outcomes.",
    "What risks have you taken in {skill} work that paid off?",
    "How do you collect feedback about your {skill} contributions?",
    "What certifications support your {skill} credibility?",
    "How have you led a {skill} training session?",
    "What pitfalls have you learned to avoid in {skill} execution?",
    "How do you prioritize multiple {skill} enhancements?",
    "What metrics matter when evaluating {skill} initiatives?",
    "How do you archive knowledge learned through {skill} experiences?",
    "Describe a situation where {skill} impacted customer outcomes.",
    "How do you collaborate with others when {skill} intersects with {domain}?",
    "How do you keep focus during long {skill} implementations?",
    "What soft skills aid your performance in {skill} roles?",
    "How do you manage expectations for {skill} deliverables?",
    "What mentoring have you provided to build {skill} capability?",
    "How do you troubleshoot problems in {skill} systems?",
    "Which emerging trends are shaping {skill} in your area?",
    "How do you validate your assumptions when applying {skill}?,",
    "How do you handle ambiguity in {skill}-oriented tasks?"
]

PROJECT_TEMPLATES = [
    "What challenges did you face in {project}?",
    "Describe the outcome of your {project}.",
    "How did you define success criteria for {project}?",
    "What role did you play in {project}?",
    "How did you prioritize work in {project}?",
    "What tools were critical for {project} execution?",
    "How did you manage risks in {project}?",
    "What stakeholders were involved in {project}?",
    "How did you measure progress during {project}?",
    "What did you do when {project} scope shifted?",
    "How did you document decisions in {project}?",
    "What was the most demanding phase of {project}?",
    "How did you transfer learnings from {project}?",
    "What innovation did you introduce in {project}?",
    "How did {project} influence your approach going forward?",
    "What governance did {project} require?",
    "How did you balance speed and quality in {project}?",
    "What team structure did {project} use?",
    "How did you handle tight deadlines in {project}?",
    "What cross-functional partners did {project} involve?",
    "How did you secure buy-in for {project}?",
    "What technical debt surfaced during {project}?",
    "How did you manage dependencies in {project}?",
    "How did you debrief after {project} completion?",
    "What would you do differently if repeating {project}?",
    "How did you track budget for {project}?",
    "How did you know when {project} was ready to launch?",
    "How did you mitigate communication challenges in {project}?",
    "What success stories emerged from {project}?",
    "What barriers did you overcome in {project}?",
    "How did you scale outcomes from {project}?",
    "What assumptions were critical in {project} planning?",
    "How did you pivot approach in {project} midstream?",
    "What quality checkpoints did you establish for {project}?",
    "How did your role in {project} evolve?",
    "What lessons did {project} teach about stakeholder alignment?",
    "What creative solution solved a {project} roadblock?",
    "How did you keep a {project} team motivated?",
    "What was the main tradeoff in {project} decisions?",
    "How did you ensure compliance in {project}?",
    "How did you manage external vendors in {project}?",
    "How did you prioritize features in {project}?",
    "What metrics were most important for {project} success?",
    "How did you turn feedback into {project} improvements?",
    "How did you ensure maintainability after {project} ended?",
    "How did you approach post-launch support for {project}?",
    "What was the hardest stakeholder conversation in {project}?",
    "How did you preserve knowledge from {project} for future teams?"
]

EXPERIENCE_TEMPLATES = [
    "Describe your experience with {experience}.",
    "How has {experience} prepared you for this role?",
    "What did you learn from {experience} that is transferable?",
    "What was your biggest contribution in {experience}?",
    "How did {experience} shape your problem-solving style?",
    "What was the most demanding part of {experience}?",
    "How did you develop your strengths through {experience}?",
    "What was a career highlight from {experience}?",
    "How did you adapt to changes during {experience}?",
    "What motivated you in {experience} work?",
    "How did you handle setbacks in {experience}?",
    "What relationships mattered during {experience}?",
    "How did you keep momentum in {experience} projects?",
    "What feedback changed your approach in {experience}?",
    "How do you compare your {experience} to current expectations?",
    "What are your proudest outcomes from {experience}?",
    "How did you manage workload across {experience} responsibilities?",
    "What was a key risk in {experience} and how did you manage it?",
    "How did you scale your impact in {experience}?",
    "What processes did you improve in {experience}?",
    "How did you communicate progress during {experience}?",
    "How did {experience} influence your ambition?",
    "What strengths helped you excel in {experience}?",
    "What did you find most rewarding about {experience}?",
    "How did you get up to speed quickly in {experience} roles?",
    "How did you collaborate with others during {experience}?",
    "How did you prioritize learning in {experience}?",
    "How did you measure your success in {experience}?",
    "What change did you lead in {experience}?",
    "How did you ensure quality in {experience} deliverables?",
    "What systems supported your {experience} execution?",
    "What tradeoffs were present in {experience} decisions?",
    "How did you manage uncertainty in {experience}?",
    "What was the biggest surprise in {experience}?",
    "How have you built on {experience} in subsequent roles?",
    "How do you bring lessons from {experience} to new contexts?",
    "How did you stay accountable in {experience}?",
    "How did you architect your workflow in {experience}?",
    "How did you mentor colleagues in {experience}?",
    "What process improvements came from {experience}?",
    "What metrics or KPIs captured {experience} success?",
    "How did you keep stakeholders aligned during {experience}?",
    "What did you learn about resilience in {experience}?",
    "How did {experience} expand your domain knowledge?",
    "What did your most mature output from {experience} look like?",
    "How did your role in {experience} evolve over time?",
    "How did you handle conflicting priorities in {experience}?",
    "What is a quick story that captures the essence of {experience}?"
]

CERTIFICATION_TEMPLATES = [
    "How has {certification} contributed to your growth?",
    "Why did you pursue {certification}?",
    "How do you apply what you learned from {certification}?",
    "What did you find most valuable in {certification} training?",
    "How did {certification} shape your credibility in {domain}?,",
    "What practical tools came from {certification}?",
    "How did {certification} affect your problem-solving?",
    "How did you prepare for {certification}?",
    "How do you keep the knowledge from {certification} current?",
    "What element of {certification} was most challenging?",
    "How did {certification} influence your project decisions?",
    "What gaps did {certification} fill in your skill set?",
    "How does {certification} relate to your current goals?",
    "What value does {certification} bring to team efforts?",
    "How did {certification} help you mentor others?",
    "How do you leverage {certification} in cross-functional discussions?",
    "What outcome improved because of {certification} knowledge?",
    "How do you prioritize new {certification} learning?",
    "How did {certification} impact your daily process?",
    "What is one instance you used {certification} approach to solve an issue?",
    "How has {certification} influenced your credibility with clients?",
    "How did {certification} change your readiness for leadership?",
    "What new mindset came from {certification} training?",
    "How did {certification} help you deliver higher quality work?",
    "How did unlocking {certification} affect your career path?",
    "How would you explain the importance of {certification} to a peer?",
    "What measurable benefit did {certification} bring?",
    "What follow-up learning have you done since {certification}?",
    "How do you share {certification} insights with your team?",
    "How has {certification} shaped your influence in {domain}?",
    "What is one best practice from {certification} you use daily?",
    "How do you validate that {certification} theory works in practice?",
    "What questions do you still have after earning {certification}?",
    "How would you use {certification} to support a cross-domain project?",
    "What is the next certification you’re considering after {certification}?",
    "How did {certification} prepare you for real-time challenges?",
    "How did you select {certification} among alternatives?",
    "How did the peer network from {certification} help your career?",
    "What weaknesses did {certification} expose?",
    "How has {certification} helped you adopt a structured approach?",
    "How did {certification} enhance your confidence in certain areas?",
    "What did you do with the capstone or case study in {certification}?",
    "How do you use {certification} to support hiring decisions?",
    "What key principle from {certification} still shapes your work?",
    "How do you align {certification} with business outcomes?",
    "What cross-domain frameworks from {certification} do you apply?",
    "How would you mentor colleagues using {certification} experience?",
    "What is a practical example of {certification} driving a positive result?"
]

SITUATIONAL_TEMPLATES = [
    "What would you do if {project} deadline was moved up unexpectedly?",
    "How would you respond if {skill} output did not meet expectations?",
    "What is your approach when a key stakeholder is unavailable during {project}?",
    "How would you handle a sudden scope change in a {domain} assignment?",
    "What steps would you take if {experience} signals indicated a quality risk?",
    "How do you proceed when you inherit incomplete work from another team?",
    "What would you do if team priorities conflict with your personal plan?",
    "How would you manage a disagreement over {skill} approach?",
    "What is your plan if resource constraints affect {project} progress?",
    "How would you react when a tight deadline impacts quality?",
    "What would you do if a critical requirement is ambiguous?",
    "How would you ensure delivery when cross-functional input is delayed?",
    "What actions would you take if a pilot in {domain} fails?",
    "How would you gain alignment on differing design opinions?",
    "What’s your approach if a peer misses a key milestone?",
    "How do you decide what to deprioritize in a busy {career} period?",
    "What would you do if your recommended solution is rejected?",
    "How would you recover from a rework request late in scope?",
    "What do you do when a customer asks for changes midproject?",
    "How would you handle competing deadlines from two stakeholders?",
    "What actions would you take if you suspect unethical behavior?",
    "How would you react to negative user feedback on a release?",
    "What is your strategy if new compliance rules affect {domain} work?",
    "How would you address low team morale during a long initiative?",
    "What would you do if you identify a root cause others missed?",
    "How would you support a colleague struggling during {project}?",
    "What steps would you take for a high-impact bug on production?",
    "How would you manage a situation where you don't know the answer?",
    "What would you do if your leader asks for a rapid decision?",
    "How would you help a new teammate ramp up quickly?",
    "What would you do if the data for a decision is incomplete?",
    "How would you handle a conflict between policy and speed?",
    "What steps would you take if you need to learn {skill} fast?",
    "How would you respond to unexpected budget cuts?",
    "What would you do if a client requests a nonstandard feature?",
    "How would you maintain quality under a new process rollout?",
    "What is your plan if your team lacks a key capability?",
    "How would you prioritize a backlog in a crisis scenario?",
    "What would you do if you are asked to lead outside your expertise?",
    "How do you ensure transparency during a failing phase?",
    "What would you do if you cannot meet a promised timeline?",
    "How do you set expectations for a risky {project}?",
    "What would you do if deadlines and quality conflict?",
    "How would you handle having to re-scope a nearly finished {project}?",
    "What would you do if your team disagrees on success metrics?",
    "How would you manage unplanned downtime in {experience} operations?",
    "How do you keep stakeholders informed in an unpredictable scenario?"
]

STRENGTH_WEAKNESS_TEMPLATES = [
    "What are your greatest strengths in {skill}?",
    "What is your most relevant strength for this {career} role?",
    "Describe a strength that boosts your performance in {domain}.",
    "How does your strength in {skill} help the team?",
    "What strength do you rely on most in challenging projects?",
    "Describe a time your {strength} moved the project forward?",
    "What area are you actively improving in {experience}?",
    "What is a weakness that has taught you a valuable lesson?",
    "How are you working to overcome a skill gap in {domain}?",
    "What self-development steps do you take for a weak area?",
    "How do you ensure your weakness doesn’t affect delivery?",
    "When did your weakness cause friction and what did you do?",
    "How is your weaker area becoming a future strength?",
    "What strengths do you bring to cross-functional collaboration?",
    "What is one soft skill you consider your biggest strength?",
    "What technical weakness are you mitigating in your current role?",
    "How do you seek support for your weaker areas in {career}?",
    "What strength helped you through a high-pressure {project}?",
    "What is one weakness you are honest about with managers?",
    "How has feedback shaped your view of your personal weaknesses?",
    "What strength have others pointed out in your recent work?",
    "What weakness did you convert into a structured improvement plan?",
    "How do you use your strengths to offset your weakest areas?",
    "Describe a situation where your strength made a difference in {experience}.",
    "What weakness do you still find hard to overcome and why?",
    "How do you avoid overusing a strength to the team’s detriment?",
    "What’s your framework for identifying new strengths to add?",
    "How do you stay objective about your own weaknesses?",
    "What strength in your {career} is most aligned with our role?",
    "What do you do when your weakness could delay a delivery?",
    "How did you identify your most critical skill gap in {domain}?",
    "How do you celebrate growth in weak areas?",
    "What strength do you leverage in mentoring others?",
    "Describe how you safeguard quality when a weakness appears?",
    "How do you determine whether to improve or delegate weak tasks?",
    "What strength do you pair with others on your team?",
    "How do you communicate your improvement journey on weaknesses?",
    "Describe a weakness that made you more resilient in {experience}.",
    "Which personal trait do you consider both a strength and a weakness?",
    "How do you prioritize training for weaknesses in {skill}?",
    "How do you choose stretch assignments aligned with your strengths?",
    "What weakness is most likely to be tested in this role and how do you handle it?",
    "What is the first strength you mention when introducing yourself?",
    "How have your strengths evolved with {experience}?",
    "What actionable improvement plan do you have for a current weakness?",
    "How do you ensure your strengths are visible to leadership?",
    "How do you ask for feedback on both your strengths and weaknesses?",
    "What’s one weakness that actually keeps you grounded professionally?"
]

LEADERSHIP_TEAMWORK_TEMPLATES = [
    "Describe a time you led a team through {project}.",
    "How do you foster collaboration in {domain} teams?",
    "What is your leadership style in {career} environments?",
    "How do you handle conflicting priorities within your team?",
    "Describe a time you built consensus on a difficult decision?",
    "How do you balance delegation and hands-on work?",
    "What strengths make you an effective teammate?",
    "How do you motivate team members during setbacks?",
    "Describe a time you coached someone to improve performance?",
    "How do you address underperformance in a peer?",
    "How do you ensure all voices are heard in team discussions?",
    "What do you do when a teammate proposes a risky idea?",
    "How do you share ownership for outcomes with your team?",
    "Describe a successful collaboration involving {domain}.",
    "How do you support new team members in their ramp-up?",
    "What do you do to promote accountability in your group?",
    "How have you driven team alignment on key objectives?",
    "What methods do you use to resolve conflicts quickly?",
    "How do you explain decisions transparently as a leader?",
    "Describe a situation where you led by example in {experience}.",
    "How do you encourage innovation while maintaining discipline?",
    "What is your approach to cross-team coordination?",
    "Describe an instance of peer leadership on a non-managerial team?",
    "How do you identify and develop emerging leaders?",
    "How have you managed remote/team-of-teams collaboration?",
    "What is your reaction to a team member taking ownership?",
    "How do you lead through uncertainty on a critical initiative?",
    "How do you ensure follow-through on team commitments?",
    "Describe how you built trust across a new team?",
    "How do you create a culture of psychological safety?",
    "How do you handle a high-performing but difficult team member?",
    "What do you do when you need to influence without authority?",
    "How do you keep a team aligned to mission and metrics?",
    "Describe how you managed a stakeholder escalation from your team?",
    "How do you recognize diverse contributions in team success?",
    "How do you build team rituals that support productivity?",
    "How do you handle competing leadership requests in {career}?",
    "Describe an example when you advocated for your team?",
    "How do you encourage accountability when outcomes are uncertain?",
    "How do you balance strategy and execution in leadership?",
    "How do you coach teams on delivering value quickly?",
    "Describe a revert-to-target strategy in a team turnaround?",
    "How do you keep people engaged during long-term initiatives?",
    "What would you do if your team resisted a process change?",
    "How do you ensure learning is shared across teams?",
    "Describe a success where teamwork outperformed individual effort?",
    "How have you built a high-performing team in {domain}?",
    "What is your process for setting team goals and tracking them?",
    "How do you foster a sense of ownership in your team?"
]

PROBLEM_SOLVING_TEMPLATES = [
    "What is your approach to solving a complex {domain} problem?",
    "Describe a time you solved a difficult issue in {project}.",
    "How do you break down problems before choosing a path?",
    "What methods do you use to identify root causes?",
    "How have you handled conflicting data in a decision?",
    "Describe a time your problem-solving saved time or cost?",
    "How do you validate assumptions in uncertain situations?",
    "What problem-solving framework do you rely on?",
    "How do you know when to iterate vs pivot in a solution?",
    "Describe your plan when you encounter a blocker on {experience}.",
    "How do you prioritize options in a constrained scenario?",
    "What do you do when initial solutions fail?",
    "Describe a creative workaround you designed for {skill} limitations?",
    "How do you manage risk when testing a new approach?",
    "How do you include stakeholders in problem framing?",
    "Describe how you gathered data to solve a critical issue?",
    "How do you handle problems that are outside your expertise?",
    "What does ‘smart failure’ look like in your process?",
    "How do you avoid analysis paralysis?",
    "How do you balance speed and accuracy in emergency fixes?",
    "Describe a non-technical obstacle you overcame in {career}.",
    "What role does feedback play in your problem-solving?",
    "How do you differentiate symptoms from causes?",
    "Describe your most impactful analysis in a complex decision?",
    "How do you structure brainstorming sessions effectively?",
    "How do you ensure your solution is sustainable long term?",
    "How do you learn from mistakes in your problem-solving journey?",
    "What continuous improvement actions do you take after closure?",
    "Describe how you adapted your solution under changing assumptions?",
    "How do you handle competing priorities while resolving a problem?",
    "How do you measure success after implementing a fix?",
    "Describe your use of evidence when making a decision?",
    "How do you manage stakeholder expectations during uncertain results?",
    "How do you assess technical debt vs new features in problem-solving?",
    "How do you ensure communication remains clear in a crisis?",
    "Describe a time you coordinated multiple teams on a resolution?",
    "How do you determine whether a problem is worth solving now?",
    "What is your technique for rapid prototyping a solution?",
    "How do you prioritize root causes when there are many?",
    "Describe an example of turning a problem into an opportunity?",
    "How do you preserve business continuity while troubleshooting?",
    "How do you make sure your solution is aligned with strategy?",
    "Describe how you have reduced reoccurrence of recurring issues?",
    "How do you handle a high-visibility problem with tight deadlines?",
    "What process do you follow for post-mortem learning?",
    "How do you balance legacy constraints and innovation?",
    "Describe a time your solution required cross-domain coordination?",
    "What is your approach to solving a problem where data is limited?"
]
